[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Demo переменные для Netlify deploy
  VITE_SUPABASE_URL = "https://demo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "demo-key"
  VITE_DEV_MODE = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
