-- Простая и безопасная миграция для добавления таблиц job_postings и urgent_jobs
-- Используем только CREATE TABLE IF NOT EXISTS для безопасности

-- Таблица работодателей
CREATE TABLE IF NOT EXISTS public.employers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  company_description text,
  company_type text CHECK (company_type IN ('restaurant', 'cafe', 'bar', 'hotel', 'catering', 'other')),
  website_url text,
  contact_email text,
  contact_phone text,
  address text,
  city_id decimal(4,1),
  logo_url text,
  is_verified boolean DEFAULT false,
  rating numeric(2,1) CHECK (rating >= 0 AND rating <= 5),
  reviews_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Таблица обычных вакансий
CREATE TABLE IF NOT EXISTS public.job_postings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  company_id uuid,
  creator_id uuid,
  city_id decimal(4,1),
  category text DEFAULT 'service',
  position_type text DEFAULT 'waiter',
  employment_type text DEFAULT 'full_time',
  schedule_type text DEFAULT 'shift',
  salary_min integer,
  salary_max integer,
  salary_type text DEFAULT 'monthly',
  currency text DEFAULT 'KZT',
  min_age integer,
  max_age integer,
  experience_required text DEFAULT 'none',
  education_required text DEFAULT 'none',
  required_skills text[],
  preferred_skills text[],
  languages_required text[],
  benefits text[],
  work_conditions text,
  address text NOT NULL,
  district text,
  metro_station text,
  contact_method text DEFAULT 'application',
  contact_person text,
  contact_phone text,
  contact_telegram text,
  contact_email text,
  status text DEFAULT 'active',
  is_urgent boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  application_deadline date,
  start_date date,
  views_count integer DEFAULT 0,
  applications_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Таблица срочных вакансий
CREATE TABLE IF NOT EXISTS public.urgent_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  company_id uuid,
  creator_id uuid,
  city_id decimal(4,1),
  address text NOT NULL,
  district text,
  position_type text NOT NULL,
  needed_date date NOT NULL,
  needed_time_start time NOT NULL,
  needed_time_end time NOT NULL,
  payment_per_shift integer NOT NULL,
  instant_payment boolean DEFAULT true,
  min_age integer,
  experience_required text DEFAULT 'none',
  application_deadline timestamptz NOT NULL,
  positions_needed integer DEFAULT 1,
  positions_filled integer DEFAULT 0,
  contact_method text DEFAULT 'telegram',
  contact_telegram text,
  contact_phone text,
  status text DEFAULT 'active',
  priority text DEFAULT 'normal',
  views_count integer DEFAULT 0,
  applications_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);