-- This script was generated by the Schema Diff utility in Supabase.
-- https://supabase.com/docs/guides/database/diff

begin;

-- Добавляем только новые поля, которых нет в текущей схеме
alter table "public"."job_postings" add column deadline timestamp with time zone;
alter table "public"."job_postings" add column tags text[];
alter table "public"."job_postings" add column benefits text[];
alter table "public"."job_postings" add column is_urgent boolean not null default false;

-- Добавляем индексы для оптимизации поиска
create index if not exists idx_job_postings_is_urgent on job_postings(is_urgent);
create index if not exists idx_job_postings_deadline on job_postings(deadline);

commit;
